### ISSUE TITLE
Please provide standalone jar file for 0.8.4.

### ISSUE THREAD

**Issue by kanaskik** [apigee/trireme#102]
I would like to use the standalone jar file for local testing of our API Proxies.
I tried to build but had errors.

**Comment by gbrail** [comment]
I'm glad to know that people had been using the releases page -- it seemed
to get little traffic before.

In the meantime, can you try "sudo npm install -g trireme?"

You can do "sudo npm install -g trireme@0.8.4" if you specifically want
that version.

On Thu, Feb 5, 2015 at 8:55 AM, Kurt Kanaskie <notifications@github.com>
wrote:

> I would like to use the standalone jar file for local testing of our API
> Proxies.
> I tried to build but had errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/102>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by kanaskik** [comment]
I've installed trireme 0.8.3 globally already and verified that the trireme-jdbc works to our Oracle DB.
`TRIREME_CLASSPATH=`pwd`/ojdbc6.jar trireme api-jdbc.js`
Since Edge v4.15.01.00 includes trireme 0.8.4, I'd like to use the standalone jar file to test locally using: 
`java -jar trireme.0.8.4.jar api-jdbc.js`
I haven't upgraded our on premise edge yet.

**Comment by gbrail** [comment]
Ah! That makes sense. Let me update the release page, I have a few minutes.

On Thu, Feb 5, 2015 at 9:59 AM, Kurt Kanaskie <notifications@github.com>
wrote:

> I've installed trireme 0.8.3 globally already and verified that the
> trireme-jdbc works to our Oracle DB.
> TRIREME_CLASSPATH=pwd/ojdbc6.jar trireme api-jdbc.js
> Since Edge v4.15.01.00 includes trireme 0.8.4, I'd like to use the
> standalone jar file to test locally using:
> java -jar trireme.0.8.4.jar api-jdbc.js
> I haven't upgraded our on premise edge yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/102#issuecomment-73070741>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by gbrail** [comment]
OK -- I updated the links on the release page. Let me know if you have any questions!

**Comment by kanaskik** [comment]
Thanks!
How to specify the JDBC driver jar file, would need this figured out for the apiproxy bundle as well.

Keep getting "Error: No suitable driver found for jdbc:oracle:thin…”
tried a few things:
TRIREME_CLASSPATH=`pwd`/ojdbc6.jar java -jar trireme.0.8.4.jar api-jdbc.js

Tried trireme-support, which says we’re running on Trireme but throws an error:
TypeError: Cannot read property "interfaceVersion" from null.


Here’s my code fragment:


var jdbc = require('trireme-jdbc');

var trireme = require('trireme-support');

if (trireme.isTrireme()) {

          console.log('We are running on Trireme.');

}

trireme.loadJars([path.join(__dirname, 'ojdbc6.jar')]);

Thanks again,
Kurt

_______________________________
Kurt Kanaskie
Web API Platform
Merck
215 993-4372 (office)
484 695-1106 (mobile)

**Comment by gbrail** [comment]
Yes, "TRIREME_CLASSPATH" is implemented by the shell script that runs the
NPM module, and it's not in the stand-alone jar.

You should be able to run "java -classpath WHATEVER.jar -jar
trireme-0.8.4.jar" and have that add the driver to the regular classpath.

If that doesn't work, then if you npm install "trireme@0.8.4" in its own
directory (without the -g option) then you can look at the script that
launches it and see what it does -- sorry it's not more convenient but we
are getting there I hope.


On Thu, Feb 5, 2015 at 10:55 AM, Kurt Kanaskie <notifications@github.com>
wrote:

> Thanks!
> How to specify the JDBC driver jar file, would need this figured out for
> the apiproxy bundle as well.
>
> Keep getting "Error: No suitable driver found for jdbc:oracle:thin…”
> tried a few things:
> TRIREME_CLASSPATH=`pwd`/ojdbc6.jar java -jar trireme.0.8.4.jar api-jdbc.js
>
> Tried trireme-support, which says we’re running on Trireme but throws an
> error:
> TypeError: Cannot read property "interfaceVersion" from null.
>
>
> Here’s my code fragment:
>
>
> var jdbc = require('trireme-jdbc');
>
> var trireme = require('trireme-support');
>
> if (trireme.isTrireme()) {
>
> console.log('We are running on Trireme.');
>
> }
>
> trireme.loadJars([path.join(__dirname, 'ojdbc6.jar')]);
>
> Thanks again,
> Kurt
>
> _______________________________
> Kurt Kanaskie
> Web API Platform
> Merck
> 215 993-4372 (office)
> 484 695-1106 (mobile)
>
> From: Greg Brail <notifications@github.com<mailto:notifications@github.com
> >>
> Reply-To: apigee/trireme <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Thursday, February 5, 2015 at 11:19 AM
> To: apigee/trireme <trireme@noreply.github.com<mailto:
> trireme@noreply.github.com>>
> Cc: Merck <kurt_kanaskie@merck.com<mailto:kurt_kanaskie@merck.com>>
> Subject: Re: [trireme] Please provide standalone jar file for 0.8.4. (#102)
>
>
> OK -- I updated the links on the release page. Let me know if you have any
> questions!
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/apigee/trireme/issues/102#issuecomment-73074740>.
> Notice: This e-mail message, together with any attachments, contains
> information of Merck & Co., Inc. (One Merck Drive, Whitehouse Station,
> New Jersey, USA 08889), and/or its affiliates Direct contact information
> for affiliates is available at
> http://www.merck.com/contact/contacts.html) that may be confidential,
> proprietary copyrighted and/or legally privileged. It is intended solely
> for the use of the individual or entity named on this message. If you are
> not the intended recipient, and have received this message in error,
> please notify us immediately by reply e-mail and then delete it from
> your system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/102#issuecomment-73082140>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by kanaskik** [comment]
Ah, with a little reverse engineering and some persistence, this works:
java -classpath `pwd`/trireme.0.8.5.jar:`pwd`/ojdbc6.jar io.apigee.trireme.shell.Main api-jdbc.js

Thanks for the hints.
Kurt

**Comment by gbrail** [comment]
Yes, I should have suggested that. Good luck!

On Fri, Feb 6, 2015 at 1:33 PM, Kurt Kanaskie <notifications@github.com>
wrote:

> Ah, with a little reverse engineering and some persistence, this works:
> java -classpath pwd/trireme.0.8.5.jar:pwd/ojdbc6.jar
> io.apigee.trireme.shell.Main api-jdbc.js
>
> Thanks for the hints.
> Kurt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/102#issuecomment-73298314>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>
