### ISSUE TITLE
How to ask a question on trireme?

### ISSUE THREAD

**Issue by gdrouet** [apigee/trireme#104]
Hi guys,

Trireme is a very interesting project. I'm working on it and I have some cool questions for you but I don't find any forum or mailing-list in the readme :-)

Any resource please?

Thanks!

**Comment by prabhatjha** [comment]
Assuming you have already seen docs at (https://github.com/apigee/trireme/tree/master/docs) , there are two places: stackoverflow and https://community.apigee.com/. We monitor both.

You could also help by filling the FAQ that I just started at https://github.com/apigee/trireme/wiki

**Comment by gdrouet** [comment]
Thanks :-)

**Comment by mikemalloyapigee** [comment]
The Apigee Edge and API Management space would be probably be best.

**Comment by gbrail** [comment]
I think it's time that Trireme had its own forum on the web, so I created a Google Group for it:

https://groups.google.com/forum/#!forum/trireme-js

The next time I update the README I'll add a link there.
