### ISSUE TITLE
Watching files with trireme does not works

### ISSUE THREAD

**Issue by gdrouet** [apigee/trireme#107]
Hi,

I try to execute the typescript compiler with trireme which exposes a "--watch" option allowing to keep the process running to see if compiled files are updated. With a ProcessBuilder, this code works:

```java
        final String[] commandLine =  new String[] { "cmd", "/c", "tsc", "--watch", "foo.ts", };

        final Process process = new ProcessBuilder(commandLine)
                .directory(new File("D:/tmp"))
                .redirectErrorStream(true)
                .start();

        final BufferedReader br = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String l;

        while ((l = br.readLine()) != null) {
            System.out.println(l);
        }
```

When I try to use a tsc compiler wrapper, the process completes instead of repeating a polling operation:

```java
        final StringBuilder sb = new StringBuilder();
        sb.append("var compile=require('typescript-compiler');var logger=require('slf4j-logger');compile([");
        sb.append("'foo.ts'],'-w --out combine.js',null,function(e){logger.logWarning(e.messageText);});");

        final File lib = new File("D:/tmp", "lib");
        lib.mkdirs();

        final OutputStream libDOs = new FileOutputStream(new File(lib, "lib.d.ts"));
        final InputStream libDIs = IOUtils.class.getResourceAsStream("/wuic/tsc/lib/lib.d.ts");

        try {
            IOUtils.copyStream(libDIs, libDOs);
        } finally {
            IOUtils.close(libDIs, libDOs);
        }

        final NodeEnvironment env = new NodeEnvironment();
        final File tmp = File.createTempFile("rhino", "watch");
        final OutputStream os = new FileOutputStream(tmp);
        IOUtils.copyStream(new ByteArrayInputStream(sb.toString().getBytes()), os);
        os.close();
        final NodeScript script = env.createScript("", tmp, null);
        script.setWorkingDirectory("D:/tmp");
        // Wait for the script to complete
        final ScriptFuture f = script.executeModule();
        f.get();
```

Behind the scene, the compiler seems to use watchFile to poll files. Fortunately, I saw that commit ad05205ffaff0adba54e60067200dc1ac5d1bd67 seems to address this issue. Could it be the case? Should I try my code with 0.8.6-SNAPSHOT?

Thanks!

**Comment by gbrail** [comment]
Sorry -- it wasn't implemented in the last release. The latest snapshot /
master branch in GitHub, however, supports "fs.watchFile," although it does
not yet support "fs.watch." It'd be great if you can try it out to make
sure it meets your needs -- we can do a release soon but I was hoping to
get a Rhino release out first.


On Sat, Feb 28, 2015 at 3:44 AM, Guillaume DROUET <notifications@github.com>
wrote:

> Hi,
>
> I try to execute the typescript compiler with trireme which exposes a
> "--watch" option allowing to keep the process running to see if compiled
> files are updated. With a ProcessBuilder, this code works:
>
>         final String[] commandLine =  new String[] { "cmd", "/c", "tsc", "--watch", "foo.ts", };
>
>         final Process process = new ProcessBuilder(commandLine)
>                 .directory(new File("D:/tmp"))
>                 .redirectErrorStream(true)
>                 .start();
>
>         final BufferedReader br = new BufferedReader(new InputStreamReader(process.getInputStream()));
>         String l;
>
>         while ((l = br.readLine()) != null) {
>             System.out.println(l);
>         }
>
> When I try to use a tsc compiler wrapper, the process completes instead of
> repeating a polling operation:
>
>         final StringBuilder sb = new StringBuilder();
>         sb.append("var compile=require('typescript-compiler');var logger=require('slf4j-logger');compile([");
>         sb.append("'foo.ts'],'-w --out combine.js',null,function(e){logger.logWarning(e.messageText);});");
>
>         final File lib = new File("D:/tmp", "lib");
>         lib.mkdirs();
>
>         final OutputStream libDOs = new FileOutputStream(new File(lib, "lib.d.ts"));
>         final InputStream libDIs = IOUtils.class.getResourceAsStream("/wuic/tsc/lib/lib.d.ts");
>
>         try {
>             IOUtils.copyStream(libDIs, libDOs);
>         } finally {
>             IOUtils.close(libDIs, libDOs);
>         }
>
>         final NodeEnvironment env = new NodeEnvironment();
>         final File tmp = File.createTempFile("rhino", "watch");
>         final OutputStream os = new FileOutputStream(tmp);
>         IOUtils.copyStream(new ByteArrayInputStream(sb.toString().getBytes()), os);
>         os.close();
>         final NodeScript script = env.createScript("", tmp, null);
>         script.setWorkingDirectory("D:/tmp");
>         // Wait for the script to complete
>         final ScriptFuture f = script.executeModule();
>         f.get();
>
> Behind the scene, the compiler seems to use watchFile to poll files.
> Fortunately, I saw that commit ad05205
> <https://github.com/apigee/trireme/commit/ad05205ffaff0adba54e60067200dc1ac5d1bd67>
> seems to address this issue. Could it be the case? Should I try my code
> with 0.8.6-SNAPSHOT?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/107>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by gdrouet** [comment]
Hi,

I just tried with 0.8.6-SNAPSHOT but it does not work. The thread is now waiting but when I change the watched file nothing is triggered. Can you take a look? You just have to create a file name "foo.ts" with some code inside in 'D:\tmp' to reproduce the issue. If you want to run the equivalent with tsc command line, just make sure you run "npm install -g typescript" brefore.

Thanks!!

**Comment by gdrouet** [comment]
Hum actually I was wrong, the only reason why the thread waits is because I invoke executeModule()...

I cloned the repository and built the three artifacts (core, kernel, node20src) with 'mvn clean install'. Anything else to do?

**Comment by gbrail** [comment]
Here's what I did to test this:

sudo npm install -g typescript

Get a Trireme repository on the "master" branch (git clone ...)

At the top level, "mvn install."

Now run the stand-alone Trireme JAR to test it. It works just like the
command line.

For instance:

java -jar jar/target/trireme.0.8.6-SNAPSHOT.jar /usr/local/bin/tsc
/tmp/hello.ts

This is just like the "trireme" command-line tool, in that it will execute
"/usr/local/bin/tsc" with the specified arguments.

This worked for me -- can you see if it works for you as well?

Now, if you're trying to embed Trireme inside another product via Java then
we might want to look at the code that you're using to do that.

On Mon, Mar 2, 2015 at 4:41 AM, Guillaume DROUET <notifications@github.com>
wrote:

> Hum actually I was wrong, the only reason why the thread waits is because
> I invoke executeModule()...
>
> I cloned the repository and built the three artifacts (core, kernel,
> node20src) with 'mvn clean install'. Anything else to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/107#issuecomment-76705272>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by gdrouet** [comment]
Yeah I'm pretty sure it will work, but I don't want to rely on tsc command because I want to write a crossplatform library which just requires a jvm. I try to run the tsc wrapper library (https://www.npmjs.com/package/typescript-compiler) on top of trireme but it seems they actually don't implement the --watch argument. The issue should not be related to trireme. I'll ask them if they can fix it first and then I'll check if you've released 0.8.6, otherwise I'll ask you for a RC.

**Comment by gdrouet** [comment]
Ok watch is going to be implemented in the tsc wrapper. I'll integrate it with trireme once released and keep you informed.

**Comment by gbrail** [comment]
Using 0.8.6 should help you address this, so I'm going to close this issue.

**Comment by gdrouet** [comment]
You're right, triereme supports it right now :)
