### ISSUE TITLE
SSLCipherTest fails with openjdk

### ISSUE THREAD

**Issue by asquare** [apigee/trireme#115]
looks like some ciphers are not available in openjdk -

$ java -version
openjdk version "1.8.0_31"

TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
TLS_DH_anon_WITH_AES_128_GCM_SHA256
testAllCiphersSupported(io.apigee.trireme.kernel.test.SSLCipherTest)  Time elapsed: 0.123 sec  <<< FAIL

testAllCiphersCount(io.apigee.trireme.kernel.test.SSLCipherTest)  Time elapsed: 0.01 sec  <<< FAILURE!
java.lang.AssertionError: expected:<71> but was:<63>

**Comment by gbrail** [comment]
Fixed this by fixing the list of SSL cipher mappings.
