### ISSUE TITLE
Missing _implicitHeader function in http.ServerResponse

### ISSUE THREAD

**Issue by gbrail** [apigee/trireme#124]
When the HTTP adapter is used, it goes down a different code path, so the undocumented _implicitHeader function is missing from http.ServerResponse.

This causes some very common code (the Expressjs "compress" middleware) to fail because those guys just love to depend on undocumented stuff. Yay Node.

The following monkey-patch, which can go anywhere as long as it's before the first HTTP response, helps:

var http = require('http');
http.ServerResponse.prototype._implicitHeader = function() {
  this.writeHead(this.statusCode);
};

**Comment by gbrail** [comment]
Fixed and tested in master with newest version of Express.

**Comment by tusharbudhe0302** [comment]
const express = require('express');
const bodyParser = require('body-parser');
const session = require('express-session');
const PORT = 9000;
const HOST = '0.0.0.0';
var rp = require('request-promise');
// App
const app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(session({
    secret: 'this-should-be-secure',
    resave: true,
    saveUninitialized: true,
    cookie: {}
}));


app.use(function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
});

app.get('/', function (req, res) {
    res.send('Hello world');
});
app.get('/posts',function (req, res) {
    var options = {
        uri: 'https://jsonplaceholder.typicode.com/posts',
        headers: {
            'User-Agent': 'Request-Promise'
        },
        json: true
    };
    rp.get(options).then( function(postsresponse){
        res.send(postsresponse);
    }).catch(function(err) {
        console.log(err);
        res.send(err);
    })
});
app.listen(PORT);
console.log('Running on http://' + HOST + ':' + PORT);

This code working correct in local but if I deployed to apigee edge I am getting exception:
{"fault":{"faultstring":"Script node executed prematurely: InternalError: syntax error (\/organization\/environment\/api\/node_modules\/hoek\/lib\/index.js#371)\nInternalError: syntax error (\/organization\/environment\/api\/node_modules\/hoek\/lib\/index.js#371)\n    at \/organization\/environment\/api\/node_modules\/request-promise\/lib\/rp.js:23\n    at module.js:456\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:364\n    at require (module.js:380)\n    at \/organization\/environment\/api\/index.js:7\n    at module.js:456\n    at module.js:474\n    at module.js:356\n    at module.js:312\n    at module.js:497\n    at startup (trireme.js:142)\n    at trireme.js:923\n","detail":{"errorcode":"scripts.node.runtime.ScriptExitedError"}}}

**Comment by whitlockjc** [comment]
That has nothing to do with this issue, so please file this in the appropriate location like the [Apigee Community](https://community.apigee.com/index.html).  Since you're here, the issue is you're attempting to use ES6 syntax in a Node.js runtime that is not ES6 compatible.
