### ISSUE TITLE
buffer and slice

### ISSUE THREAD

**Issue by DavidApfel** [apigee/trireme#143]
Not sure if this is a bug or just different behaviour than with node, but when using for example the bn.js module with trireme it's a problem.  

When using trireme and create a buffer and try to get a minus index [-1] of the buffer it gives an ArrayIndexOutOfBoundsException. When I create then a second buffer with slice() from the first buffer and then try to get a minus index it gives a value. While using node I get undefined in both cases:

```
var buf1 = new Buffer("1111", "hex");
var buf2 = buf1.slice(1);
```

trireme:

```
console.log(buf1[-1]); // java.lang.ArrayIndexOutOfBoundsException: -1
console.log(buf2[-1]); // 17
```

node:

```
console.log(buf1[-1]); // undefined
console.log(buf2[-1]); // undefined
```

**Comment by gbrail** [comment]
Thanks for trying this. If trireme works differently from Node 0.10 in this
regard then it's a Trireme bug that wasn't caught by one of the regression
tests. This should not be too hard to fix...


On Wed, Jan 27, 2016 at 10:09 AM, DavidApfel <notifications@github.com>
wrote:

> Not sure if this is a bug or just different behaviour than with node, but
> when using for example the bn.js module with trireme it's a problem.
>
> When using trireme and create a buffer and try to get a minus index [-1]
> of the buffer it gives an ArrayIndexOutOfBoundsException. When I create
> then a second buffer with slice() from the first buffer and then try to get
> a minus index it gives a value. While using node I get undefined in both
> cases:
>
> var buf1 = new Buffer("1111", "hex");
> var buf2 = buf1.slice(1);
>
> trireme:
>
> console.log(buf1[-1]); // java.lang.ArrayIndexOutOfBoundsException: -1
> console.log(buf2[-1]); // 17
>
> node:
>
> console.log(buf1[-1]); // undefined
> console.log(buf2[-1]); // undefined
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/143>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by DavidApfel** [comment]
Yes, Trireme works differently from Node v0.10.32. Thanks!
