### ISSUE TITLE
TLS 1.2 support 

### ISSUE THREAD

**Issue by dzhivushko** [apigee/trireme#149]
Hello,
I'm using Trireme (in Apigee cloud).
I have an issue with simple https request. I see the **'Error: Socket hung up;'** when trying to make request to one of our back end services. As I know this back end was changed and now it supports TLS 1.2 only and it  is a cause why code started to throw these errors. I have tried to investigate what can be a cause and was able to find only one thing: error appears only if I run code using Trireme. It works  if I run the same code using Node.

Unfortunately I can't provide exact code example because our back end is not available via public URL. I was not able to find any public URL which allows to reproduce 'socket hang up error'. But found example which shows similar situation when code works on Node and doesn't work using Trireme. The error is not the same - it throws 'handshake' error instead. But if someone can explain - it will be helpful

```
var request = require('request').defaults({timeout: 60000});

var postCfg = {
 url: 'https://tls1test.salesforce.com '
};

request.get(postCfg, function(err, resp, body) {
  console.log('err' , err);
  console.log('body' , body);
});

```

package.json
```
{
  "name": "sample",
  "version": "1.1.8",
  "private": "true",
  "description": "",
  "dependencies": {
    "request": "^2.72.0"
  },
  "devDependencies": {

  },
  "scripts": {
    "start": "trireme app.js"
  }
}

```

I understand that there is something specific related to the SSL. But may be a bug or can be improved in Trireme. Can someone help?

**Comment by gbrail** [comment]
This works for me with Java 8 but not with Java 7. I'll see if I can dig in to some Java 7 options that can make this work.

**Comment by gbrail** [comment]
..since the Apigee Edge cloud runs on Java 7...

**Comment by dzhivushko** [comment]
Hello Greg

Today I got the response from Apigee support with reference to this https://community.apigee.com/questions/9735/enforce-tls-12-protocol-for-all-outbound-connectio.html

Last week I've tried usage of 'secureProtocol' but I've used constant value 'TLSv1_2_method'  instead of 'TLSv1.2'.  I believe it is cause why it didn't work for me.

I'm out of office today. Will try 'secureProtocol=TLSv1.2' tomorrow and close this issue if it works

**Comment by gbrail** [comment]
yes, that works for me too. Basically, we have to trick Java 7's TLS to
work in the right mode.

Here's what I ended up putting in app.js:

var request = require('request').defaults(
        {
                timeout: 60000,
                agentOptions: {
                        secureProtocol: 'TLSv1.2',
                }
        }
);

On Mon, May 23, 2016 at 9:22 AM, Dmitry Zhivushko <notifications@github.com>
wrote:

> Hello Greg
>
> Today I got the response from Apigee support with reference to this
> https://community.apigee.com/questions/9735/enforce-tls-12-protocol-for-all-outbound-connectio.html
>
> Last week I've tried usage of 'secureProtocol' but I've used constant
> value 'TLSv1_2_method' instead of 'TLSv1.2'. I believe it is cause why it
> didn't work for me.
>
> I'm out of office today. Will try 'secureProtocol=TLSv1.2' tomorrow and
> close this issue if it works
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/149#issuecomment-221022392>
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by dzhivushko** [comment]
Hello Greg,
Sorry for very long delay. I closed the support case in Apigee portal but forgot about this.

Yes, the option  secureProtocol: 'TLSv1.2' fixes the issue.
The error I reported was caused by invalid value. I used 'TLSv1_2_method' (invalid!!!) instead of 'TLSv1.2'
