### ISSUE TITLE
Nodejs implementation

### ISSUE THREAD

**Issue by CailinPitt** [apigee/trireme#150]
This may be a silly issue on my part, but I have Node v0.10.32 installed on Windows 7. Whenever I try to run the following snippet:
```java
NodeEnvironment env = new NodeEnvironment();
NodeScript script = env.createScript("./test.js", new File("./test.js"), null);
```
test.js simply contains `print("nodejs");`

I get an `No available Node.js implementation matches version null` error. Any suggestions?

**Comment by CailinPitt** [comment]
After digging through the release notes I saw that I was missing the `trireme-node10src` dependency. Everything is working great now that I added it. I appreciate all of your work on Trireme, Greg.

**Comment by DinoChiesa** [comment]
Hi Cailin


I suggest you try asking a question on community.apigee.com.


The "issues list" for trireme is more like a bug list, rather than a general Q&A forum.


________________________________
