### ISSUE TITLE
require("os").arch() returns different values than on node.js

### ISSUE THREAD

**Issue by mberndt123** [apigee/trireme#154]
Hi,

on node.js, require("os").arch() will return "x64" on an x86-64 machine, while Trireme will return "amd64" instead. This incompatible behavior causes breakage in the phantomjs-bin package from npm.

**Comment by whitlockjc** [comment]
I cannot reproduce this anymore.  Running `require("os").arch()` in Trireme produces `x86` as expected.

**Comment by mberndt123** [comment]
I'm sorry, but the bug is still present. If it prints `x86` on your machine, then you're probably using a 32-bit JVM. On a 64-bit JVM on Linux with trireme 0.9.0, I still get the behaviour I described.

**Comment by whitlockjc** [comment]
`x86` was a typo, should had been `x64`.  I just ran this test and here is the output:

**node**

```
node --version
v0.10.48
node -e 'console.log(require("os").arch())'
x64
```

**trireme**

```
trireme --version
Trireme 0.9.0
node 0.10.32 (default)
node 0.12.7
trireme -e 'console.log(require("os").arch())'
x64
```

I'm on a Mac, maybe that's the difference.  Let me try this on a Linux VM and I'll let you know if anything is different.

**Comment by mberndt123** [comment]
Hey @whitlockjc, did you have a chance to look into this?

**Comment by whitlockjc** [comment]
I can reproduce this on Ubuntu using VirtualBox.  It seems like [AbstractProcess.java#getArch](https://github.com/apigee/trireme/blob/2079152901770ddf9c0910f79a8f42289e1fa8b1/core/src/main/java/io/apigee/trireme/core/internal/AbstractProcess.java#L172) needs to be updated to handle `amd64` as being an `x64` equivalent.  Seems like an easy fix.

**Comment by whitlockjc** [comment]
What's interesting is that this might be working as intended.  Basically, Java doesn't have a way to get the CPU architecture and `os.arch` _(which Trireme uses)_ is the bitness of the JRE and not of the CPU architecture.  We _could_ update `AbstractProcess#getArch` to handle `amd64` as `x64` but even that isn't a guarantee.  Maybe @gbrail can give an opinion and I'll just do the necessary work _(if any)_.

**Comment by whitlockjc** [comment]
If you're running at 32-bit JVM on a 64-bit machine, node.js would report `x64` while Trireme would report `x86` because while the CPU architecture is 64-bit, the JVM is 32-bit and `os.arch` is the bitness of the JVM and **not** the CPU.

**Comment by gbrail** [comment]
Originally I had os.arch() on Trireme just return "Java" because, well, why
does it matter? If we're running on the JVM anyway so it really doesn't
matter.

However, this caused a compatibility problem for something -- and I forget
what -- so at some point I started having it return real-ish things like
"x86."

Like many things in Node, there's no spec or docs that tells us what the
possible values are, so we have to guess, unless someone knows where to go
for more research.

So the question is, why does anyone check this? What decisions are made by
various Node packages based on this value?

If we know that perhaps we can figure out how to make a more sustainable
fix here. Thanks!

**Comment by mberndt123** [comment]
Regarding use cases: as I mentioned in my original report, the phantomjs-bin package from npm breaks because of this. It contains binaries for different architectures and operating systems which are stored in directories whose names correspond to the respective architectures, and then there's some JavaScript that messes around with `os.arch()` to figure out which binary is the right one. Take a look at it [here](https://github.com/eugeneware/phantomjs-bin/blob/master/index.js). It seems plausible to me that other packages containing binaries do similar things.

There's an "archs" module on npmjs.org that claims to list all architectures supported by node. The relevant part seems to be this: https://github.com/sindresorhus/archs/blob/master/index.js, that is arm, ia32 and x64.
