### ISSUE TITLE
Trireme mvn install fails on testSecurePair()

### ISSUE THREAD

**Issue by yuriylesyuk** [apigee/trireme#155]
While building trireme locally I am getting failed test: 
[INFO] Reactor Summary:
[INFO] 
[INFO] trireme ............................................ SUCCESS [  3.728 s]
[INFO] trireme-kernel ..................................... SUCCESS [  7.440 s]
[INFO] trireme-core ....................................... SUCCESS [  1.735 s]
[INFO] rhino-compiler ..................................... SUCCESS [  6.186 s]
[INFO] trireme-node10 ..................................... SUCCESS [  0.025 s]
[INFO] trireme-node10src .................................. FAILURE [ 10.757 s]
[INFO] trireme-node12 ..................................... SKIPPED
[INFO] trireme-node12src .................................. SKIPPED

Tests in error: 
  testSecurePair(io.apigee.trireme.node10.test.BasicTest): org.mozilla.javascript.JavaScriptException: [object Object] (assert.js#93)

I looked at the travis job status:
https://travis-ci.org/apigee/trireme/builds/170550116

And it failed with same error 7 months ago. See detailed log at the link.

Any ideas what can be done?

Regards

**Comment by gbrail** [comment]
The failing test is trying to check the list of supported ciphers against
names that Node.js should recognize, and what comes out of Java doesn't
quite match up when the tests are run on Java 8. I think it's a matter of
fixing the cipher list.
