### ISSUE TITLE
Is this project dying or is it still maintained?

### ISSUE THREAD

**Issue by legatoloco** [apigee/trireme#158]
I noticed that the last commit is 9 months old while all other commits are more like 2 years old.
Is this project still maintained? are there plans for it?

**Comment by gbrail** [comment]
We have a few people who can fix bugs that come up. However, no one is actively working on making Trireme work with newer versions of Node. Doing that requires a lot of new features in Rhino, which is actually a bit harder. Furthermore, most of the issues that people have (versus Node 0.10) are in Rhino and not in Trireme.

Of course it's an open source project and you're welcome to contribute or suggest things that you'd like to see happen.
