### ISSUE TITLE
Using jsdom on Trireme (Windows)

### ISSUE THREAD

**Issue by chris-h-sg** [apigee/trireme#80]
Is it possible to run jsdom on Trireme?
On Windows, I have jsdom installed and working in my regular NodeJS installation. However, when I'm trying to run

```
require("jsdom");
```

in Trireme, I'm getting an exception saying `ReferenceError: "MZ" is not defined.`

Ultimately, this is coming from jsdom trying to load `contextify.node`, which is a binary file and happens to start with the characters `MZ`.

Stack trace:

```
"MZ" is not defined.
    at C:\Users\Chris\node_modules\jsdom\node_modules\contextify\build\Release\contextify.node:1
    at module.js:456
    at module.js:474
    at module.js:356
    at module.js:312
    at module.js:364
    at require (module.js:380)
    at bindings (C:\Users\Chris\node_modules\jsdom\node_modules\contextify\node_modules\bindings\bindings.js:76)
    [...]
```

Is there a way to do this with Trireme?

**Comment by alex88** [comment]
@gbrail what's the current way to be able to use contextify?

**Comment by gbrail** [comment]
It should "just work." The module is written in JS and depends on a native
module that is normally compiled using NPM from the C++ source. Trireme has
a Java implementation of that native module in the "trireme-util" module.
So, I'd appreciate it if someone could try the latest version, and then we
can look and see if something needs to be fixed.

On Mon, Sep 7, 2015 at 6:21 AM, Alessandro Tagliapietra <
notifications@github.com> wrote:

> @gbrail <https://github.com/gbrail> what's the current way to be able to
> use contextify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/80#issuecomment-138296591>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>
