### ISSUE TITLE
Using Tuffle and Graal instead of Rhino for performance?

### ISSUE THREAD

**Issue by patsimon** [apigee/trireme#85]
I have no idea of how difficult it would be to implement but just wondering if it would be worth looking at Truffle and Graal (http://www.oracle.com/technetwork/oracle-labs/program-languages/javascript/index.html) instead of Rhino for performance benefits?

**Comment by gbrail** [comment]
Truffle and Graal sound neat, but just like Nashorn, they are very different from Rhino. I'm going to close this, but perhaps if we find someone to pick up work on Rowboat, we can look at alternative scripting engines there as well.
